name = "CropRootBox"
uuid = "0b8d6067-eb21-45e9-ba5b-895cd2a7ad38"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]
version = "0.1.14-DEV"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Cropbox = "a904b226-abf1-11e9-2713-059ba252a964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PlyIO = "42171d58-473b-503a-8d5f-782019eb09ec"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SimpleCrop = "d8d364f4-8e31-46ec-8830-5c8affd8de2c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
GeometryBasics = "0.5"
Colors = "0.12"
CoordinateTransformations = "0.6"
Cropbox = "0.3"
Distributions = "0.23, 0.24, 0.25"
FileIO = "1"
Meshing = "0.5, 0.6"
Rotations = "1"
WriteVTK = "1"
